export const COMMON_UI = {
  CURRENCY_SYMBOL: '৳',
  PRICE_LABELS: {
    WAS: 'was',
    SAVE: 'Save',
    SAVINGS: 'savings',
  },
  ACTIONS: {
    LEARN_MORE: 'Learn More',
    SHOP_NOW: 'Shop Now',
    VIEW_DETAILS: 'View Details',
    ADD_TO_CART: 'Add to Cart',
    QUICK_ADD_TO_CART: 'Quick Add to Cart',
    CONTINUE_SHOPPING: 'Continue Shopping',
    BACK_TO_HOME: 'Back to Home',
    PROCEED_TO_CHECKOUT: 'Proceed to Checkout',
    SEND_MESSAGE: 'Send Message',
    SHOP_OUR_PRODUCTS: 'Shop Our Products',
  },
  BADGES: {
    MOST_POPULAR: 'Most Popular',
    NEW_FORMULA: 'New Formula',
    MADE_IN_BANGLADESH: 'Made in Bangladesh',
    FEATURED: 'Featured',
  },
  ICONS: {
    STAR: 'fas fa-star',
    SHOPPING_CART: 'fas fa-shopping-cart',
    ENVELOPE: 'fas fa-envelope',
    ARROW_RIGHT: 'fas fa-arrow-right',
    ARROW_LEFT: 'fas fa-arrow-left',
    CHEVRON_LEFT: 'fas fa-chevron-left',
    CHEVRON_RIGHT: 'fas fa-chevron-right',
    CHEVRON_DOWN: 'fas fa-chevron-down',
    CHECK_CIRCLE: 'fas fa-check-circle',
    HEART: 'fas fa-heart',
    SHIELD_ALT: 'fas fa-shield-alt',
    TOOTH: 'fas fa-tooth',
    LEAF: 'fas fa-leaf',
    SPARKLES: 'fas fa-sparkles',
    CERTIFICATE: 'fas fa-certificate',
    MICROSCOPE: 'fas fa-microscope',
    AWARD: 'fas fa-award',
    CLOCK: 'fas fa-clock',
    SEARCH: 'fas fa-search',
    DROPLET: 'fas fa-droplet',
    REFRESH: 'fas fa-refresh',
    USERS: 'fas fa-users',
    FLAG: 'fas fa-flag',
    BULLSEYE: 'fas fa-bullseye',
    EYE: 'fas fa-eye',
    MEDKIT: 'fas fa-medkit',
    GRADUATION_CAP: 'fas fa-graduation-cap',
    CLINIC_MEDICAL: 'fas fa-clinic-medical',
    SEEDLING: 'fas fa-seedling',
    HANDS_HELPING: 'fas fa-hands-helping',
    MAP_MARKER_ALT: 'fas fa-map-marker-alt',
    PHONE: 'fas fa-phone',
    TRUCK: 'fas fa-truck',
    BALANCE_SCALE: 'fas fa-balance-scale',
    QUOTE_LEFT: 'fas fa-quote-left',
    TIMES: 'fas fa-times',
    MINUS: 'fas fa-minus',
    PLUS: 'fas fa-plus',
    EXPAND_ARROWS_ALT: 'fas fa-expand-arrows-alt',
  },
} as const;
